dogoweb/dogoweb/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.views.generic.base import RedirectView
from stats import views as stats_views
from spam import views as spam_views

urlpatterns = [
    url(r'favicon.ico', RedirectView.as_view(url='/static/dogoweb/img/favicon.ico', permanent=True)),
    url(r'^$', RedirectView.as_view(pattern_name='pizarron', permanent=False)),
    url(r'pizarron', stats_views.pizarron, name='index'),
    url(r'config', spam_views.config, name='config'),
    path('seg/', include('seg.urls')),
    path('mail/', include('mail.urls')),
    path('spam/', include('spam.urls')),
    path('erp/', include('erp.urls')),
    path('stats/', include('stats.urls')),
    path('admin/', admin.site.urls),
]# + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

dogoweb/erp/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='erpindex'),
    url(r'^clientes$', views.clientes, name='erp_clientes'),
    url(r'^cliente/create/$', views.cliente_create, name='erp_cliente_create'),
    url(r'^cliente/update/(?P<pks>[\,\d]+)*$', views.cliente_update, name='erp_cliente_update'),
    url(r'^cliente/delete/(?P<pks>[\,\d]+)*$', views.cliente_delete, name='erp_cliente_delete'),
]

dogoweb/spam/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='spamindex'),
    url(r'^lists$', views.lists, name='spamlists'),
    url(r'^list$', views.lista, name='spam_list'),
    url(r'^list/create/$', views.lista_create, name='spam_list_create'),
    url(r'^list/update/(?P<pks>[\,\d]+)*$', views.lista_update, name='spam_list_update'),
    url(r'^list/delete/(?P<pks>[\,\d]+)*$', views.lista_delete, name='spam_list_delete'),
    url(r'^avirus$', views.avirus, name='spamavirus'),
    url(r'^modules$', views.modules, name='spammodules'),
    url(r'^module$', views.module, name='spam_module'),
    url(r'^module/create/$', views.module_create, name='spam_module_create'),
    url(r'^module/update/(?P<pks>[\,\d]+)*$', views.module_update, name='spam_module_update'),
    url(r'^module/delete/(?P<pks>[\,\d]+)*$', views.module_delete, name='spam_module_delete'),
    url(r'^policies$', views.policies, name='spampolicies'),
    url(r'^policy$', views.policy, name='spam_policy'),
    url(r'^policy/create/$', views.policy_create, name='spam_policy_create'),
    url(r'^policy/update/(?P<pks>[\,\d]+)*$', views.policy_update, name='spam_policy_update'),
    url(r'^policy/delete/(?P<pks>[\,\d]+)*$', views.policy_delete, name='spam_policy_delete'),
    url(r'^rules$', views.rules, name='spamrules'),
    url(r'^rulessearch/$', views.rules_search, name='spamrulesearch'),
    url(r'^rules/create/$', views.rules_create, name='spam_rule_create'),
    url(r'^rules/update/(?P<pks>[\,\d]+)*$', views.rules_update, name='spam_rule_update'),
    url(r'^rules/delete/(?P<pks>[\,\d]+)*$', views.rules_delete, name='spam_rule_delete'),
    url(r'^rules/up/(?P<ids>[\,\d]+)*$', views.rules_up, name='spam_rule_up'),
    url(r'^rules/down/(?P<ids>[\,\d]+)*$', views.rules_down, name='spam_rule_down'),
    url(r'^autorules$', views.autorules, name='spamautorules'),
    url(r'^autorulesp$', views.autorulesp, name='spamautorulesp'),
    url(r'^aurorulessearch/$', views.autorules_search, name='spamautorulesearch'),
    url(r'^autorules/confirm/(?P<ids>[\,\d]+)*$', views.autorules_confirm, name='spam_autorule_confirm'),
    url(r'^autorules/ignore/(?P<ids>[\,\d]+)*$', views.autorules_ignore, name='spam_autorule_ignore'),
    url(r'^autorules/flip/(?P<ids>[\,\d]+)*$', views.autorules_flip, name='spam_autorule_flip'),
    url(r'^autorules/show/(?P<ids>[\,\d]+)*$', views.autorules_show, name='spam_autorule_show'),
]

dogoweb/spam/models.py
from django.db import models
from django.apps import apps
from django.utils import timezone
from django.utils.translation import gettext as _
from django.contrib.auth.models import User
from django.template.loader import render_to_string

from seg.models import DTManager, html_check
from erp.models import Cliente
from dogoweb.settings import VERSION, ICO_OK, ICO_WARN, ICO_INFO, ICO_CRIT


# Modelo de modulos
class Modulo(models.Model):
    objects=DTManager()

    nombre = models.CharField('Name', max_length=50, unique=True)
    activo = models.BooleanField('Active', default=True)
    config = models.TextField('Configuration', default='')

    def __repr__(self):
        return '<Modulo: nombre="%s">' % self.nombre

    def __str__(self):
        return self.nombre

    class Meta:
        ordering = ["nombre"]
        permissions = (
            ("view_modules", "View menu modules"),
            ("manage_modules", "Manage modules"),
        )

    def probar(self, datos):
        return False


# Modelo de politicas
class Politica(models.Model):
    objects=DTManager()

    nombre = models.CharField('Name', max_length=50, unique=True)
    activo = models.BooleanField('Active', default=True)

    def __repr__(self):
        return '<Politica: nombre="%s">' % self.nombre

    def __str__(self):
        return self.nombre

    class Meta:
        ordering = ["nombre"]
        permissions = (
            ("view_politicas", "View menu policies"),
            ("manage_politicas", "Manage policies"),
        )

    def probar(self, datos):
        return False


# Modelo de politicas
TIPO_LISTAS = (
    ('blanca', 'Blanca'),
    ('negra', 'Negra'),
    ('rapida', 'Rápida'),
    ('nosa', 'No SA'),
    ('cliente', 'Cliente'),
)

TIPO_LISTAS_SRCH = (
    ('', '-'),
    ('blanca', 'Blanca'),
    ('negra', 'Negra'),
    ('rapida', 'Rápida'),
    ('nosa', 'No SA'),
    ('cliente', 'Cliente'),
)


class Listas(models.Model):
    objects=DTManager()

    tipo = models.CharField('Type', max_length=10, choices=TIPO_LISTAS, default='blanca', db_index=True)
    ip = models.CharField('IP', max_length=15, db_index=True)
    remitente = models.CharField('Sender', max_length=180, db_index=True)
    destino = models.CharField('Recipient', max_length=100, default='%', db_index=True)
    activo = models.BooleanField('Active', default=True)
    creado_el = models.DateTimeField('Created', auto_now_add=True)
    cambiado_el = models.DateTimeField('Updated', auto_now=True)

    def __repr__(self):
        return '<Listas: tipo="%s", ip="%s", rem="%s", dest="%s">' % (self.tipo, self.ip, self.remitente, self.destino)

    def __str__(self):
        return self.tipo + ": " + self.ip

    class Meta:
        ordering = ["ip", "remitente", "destino"]
        permissions = (
            ("view_listas", "View menu listas"),
            ("manage_listas", "Manage listas"),
        )
        unique_together = ("tipo", "ip", "remitente", "destino")


TEST_REGLA = (
    (2, 'por IP'),
    (3, 'por Remitente'),
    (4, 'por Asunto'),
    (5, 'por Cuerpo'),
)


class AutoReglas(models.Model):
    objects=DTManager()

    rdogoid = models.IntegerField('dogo ID', db_index=True)
    dogo = models.ForeignKey('mail.Dogomail', on_delete=models.PROTECT)
    testid = models.IntegerField('Test', choices=TEST_REGLA, db_index=True)
    valor = models.CharField('Value', max_length=255)
    activo = models.BooleanField('Active', default=True)
    hora = models.DateTimeField('Time')
    cantidad = models.IntegerField('Count')
    descripcion = models.CharField('Description', max_length=255)
    confirmada = models.BooleanField('Confirmed', default=False)
    cambiado_el = models.DateTimeField('Updated', auto_now=True)

    def __repr__(self):
        return '<AutoReglas: id="%d", rdogoid="%d", dogo="%s", valor="%s">' % \
               (self.id, self.rdogoid, self.dogo.nombre, self.valor)

    def __str__(self):
        return str(self.id)

    class Meta:
        ordering = ["hora"]
        permissions = (
            ("manage_autorules", "Manage AutoRules"),
        )
        unique_together = ['dogo', 'rdogoid']

    def get_confirmada_display(self):
        return html_check(bool(self.confirmada))

    def get_activo_display(self):
        return html_check(bool(self.activo))

    @classmethod
    def set_ignored(cls, pks):
        data = dict()
        fallo = False
        Mensaje = apps.get_model('mail', 'Mensaje')
        AccionDogo = apps.get_model('mail', 'AccionDogo')
        idpks = [int(idp) for idp in pks.split(',')]
        rules = cls.objects.filter(id__in=idpks)
        for r in rules:
            r.activo = False
            mpks = [idm.id for idm in r.mensaje_set.all()]
            mret = Mensaje.cambiar_estado(mpks, 'send')
            if mret['mensaje']['tipo'] == 'critical':
                fallo = True
            r.save()
            try:
                nact = {
                    'dogo': r.dogo,
                    'rdogotp': 'reglas',
                    'rdogoid': r.rdogoid,
                    'rcampo': 'activo',
                    'rvalor': '0',
                }
                oact = AccionDogo(**nact)
                oact.save()
            except:
                fallo = True
        if fallo:
            data['mensaje'] = {
                'icon': ICO_CRIT,
                'msg': _('The rules were not marked to be ignored'),
                'tipo': 'critical',
            }
        else:
            data['mensaje'] = {
                'icon': ICO_OK,
                'msg': _('The rules were marked to be ignored'),
                'tipo': 'success',
            }
        return data

    @classmethod
    def set_confirmed(cls, pks):
        data = dict()
        fallo = False
        Mensaje = apps.get_model('mail', 'Mensaje')
        AccionDogo = apps.get_model('mail', 'AccionDogo')
        idpks = [int(idp) for idp in pks.split(',')]
        rules = cls.objects.filter(id__in=idpks)
        for r in rules:
            r.confirmada = True
            mpks = [idm.id for idm in r.mensaje_set.all()]
            mret = Mensaje.cambiar_estado(mpks, 'trash')
            if mret['mensaje']['tipo'] == 'critical':
                fallo = True
            r.save()
        try:
            nact = {
                'dogo': r.dogo,
                'rdogotp': 'reglas',
                'rdogoid': r.rdogoid,
                'rcampo': 'confirmada',
                'rvalor': '1',
            }
            oact = AccionDogo(**nact)
            oact.save()
        except:
            fallo = True
        if fallo:
            data['mensaje'] = {
                'icon': ICO_CRIT,
                'msg': _('The rules were not marked to be confirmed'),
                'tipo': 'critical',
            }
        else:
            data['mensaje'] = {
                'icon': ICO_OK,
                'msg': _('The rules were marked to be confirmed'),
                'tipo': 'success',
            }
        return data

    @classmethod
    def flip(cls, pks):
        data = dict()
        fallo = False
        AccionDogo = apps.get_model('mail', 'AccionDogo')
        idpks = [int(idp) for idp in pks.split(',')]
        rules = cls.objects.filter(id__in=idpks)
        for r in rules:
            r.activo = not r.activo
            r.save()
        try:
            nact = {
                'dogo': r.dogo,
                'rdogotp': 'reglas',
                'rdogoid': r.rdogoid,
                'rcampo': 'activo',
                'rvalor': str(int(r.activo)),
            }
            oact = AccionDogo(**nact)
            oact.save()
        except:
            fallo = True
        if fallo:
            data['mensaje'] = {
                'icon': ICO_CRIT,
                'msg': _('The rules were not fliped'),
                'tipo': 'critical',
            }
        else:
            data['mensaje'] = {
                'icon': ICO_OK,
                'msg': _('The rules were fliped'),
                'tipo': 'success',
            }
        return data

    @classmethod
    def html_show(cls, pks, request):
        data = dict()
        mpks = list()
        Mensaje = apps.get_model('mail', 'Mensaje')
        try:
            idpks = [int(idp) for idp in pks.split(',')]
            rules = cls.objects.filter(id__in=idpks)
            for r in rules:
                mpks+=[idm.id for idm in r.mensaje_set.all()]
            msgs = list()
            for m in Mensaje.objects.filter(id__in=mpks):
                msgs.append({
                    'estado': m.get_estado_html(),
                    'rcv_time': m.rcv_time.strftime("%d/%m/%Y %H:%M:%S"),
                    'sender': m.sender,
                    'ip_orig': m.ip_orig,
                    'subject': m.subject,
                    'recipients': ','.join([r.receptor for r in m.destinatario_set.all()]),
                })
            context = {
                'msgs': msgs,
            }
            data['html_form'] = render_to_string('spam/form_show_autorulemsgs.html', context, request=request)
        except Exception as e:
            data['mensaje'] = {
                'icon': ICO_CRIT,
                'msg': _('The item had a problem, please review'),
                'tipo': 'critical',
            }
        return data

    @classmethod
    def filtro_usuario(self, user, jbody):
        if user.groups.count() > 0:
            clients = False
            operator = False
            for g in user.groups.all():
                if g.name == 'clients':
                    clients = True
                if g.name == 'operator':
                    operator = True
            if clients or operator:
                # Busco los clientes que tiene asignado el usuario por dominio
                clis = set()
                for d in user.dominio_set.all():
                    clis.add(d.cliente.id)
                if len(clis) > 0:
                    if 'colhidden' in jbody:

dogoweb/spam/templates/spam/autorules.html
{% extends "base_menu.html" %}
{% load i18n %}
{% load seg_tags %}
{% block titulo %}{% trans "Autorules" %}{% endblock %}

{% block encabezadomenu %}
    <script>var noTZ; if ("{% settings_value "DBENGINE" %}" == "mysql") { noTZ=true; } else { noTZ=false; } </script>
    <script src="/static/spam/js/autorules.js"></script>
{% endblock %}

{% block contenidomenu %}
<div class="row row-top-15">
    <div class="col-lg-2">
        <section class="panel panel-with-borders panel-compact">
            <div class="panel-heading">
                <h5><small><i class="icmn-search"></i></small> {% trans "Search" %}</h5>
            </div>
            <div class="panel-body">
                {% with WIDGET_BASE_CLASS='form-control' WIDGET_GROUP_CLASS='form-group' WIDGET_REQUIRED_CLASS='form-control-required' WIDGET_ERROR_LIST_CLASS='form-control-error' WIDGET_ERROR_CLASS='has-danger' %}
                <form id='busca_form' method="post">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-lg-6">
                            <button type="button" class="btn" onclick="document.getElementById('busca_form').reset();{{ form.activo.id_for_label }}_rd_reset();{{ form.confirmada.id_for_label }}_rd_reset();jobj.buscar();">{% trans "Clear" %}</button>
                        </div>
                        <div class="col-lg-6 text-right">
                            <button type="button" class="btn btn-primary" id="id_btn_buscar" onclick="jobj.buscar();">{% trans "Search" %}</button>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="form-group">
                                <input type="text" name="descripcion" class="form-control" id="id_descripcion" placeholder='{% trans "Name" %}'/>
                                <script>$('#id_descripcion').focus();</script>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="form-group">
                                <input type="text" name="valor" class="form-control" id="id_valor" placeholder='{% trans "Value" %}'/>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-6 col-compact-left">
                            {% render_field_full_checkboxnull form.confirmada %}
                        </div>
                        <div class="col-lg-6 col-compact-right">
                            {% render_field_full_checkboxnull form.activo %}
                        </div>
                    </div>
                    <div id="gr_msgcant" class="form-group">
                        <div class="row">
                            <div class="col-lg-12">
                                <label class="form-control-label" for="id_rcv_from">{% trans "Message Count" %}</label>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-6 col-compact-left">
                                    <input type="text" name="mincant" class="form-control" id="id_mincant" placeholder="{% trans 'Min' %}"/>
                            </div>
                            <div class="col-lg-6 col-compact-right">
                                <input type="text" name="maxcant" class="form-control" id="id_maxcant" placeholder="{% trans 'Max' %}"/>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="row">
                            <div class="col-lg-12">
                                <label class="form-control-label" for="id_rcv_from">{% trans "Date" %}</label>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-12">
                                <input type="text" name="rcv_from" class="form-control datetimepicker-init" id="id_rcv_from" placeholder='{% trans "From" %}'>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-12">
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-12">
                                <input type="text" name="rcv_until" class="form-control datetimepicker-init" id="id_rcv_until" placeholder='{% trans "To" %}'>
                            </div>
                        </div>
                    </div>
                </form>
                {% endwith %}
            </div>
        </section>
    </div>
    <div class="col-lg-10">
        <section class="panel panel-with-borders panel-compact">
            <div class="panel-heading">
                {% if perms.spam.change_autoreglas %}
                <button type="button" id="ignorerule" onclick="jobj.changeRule('ignore');" class="btn btn-success btn-sm pull-right panel-buttons-sm width-120" title="{% trans 'Deactivate rule and send blocked emails' %}"><i class="icmn-forward"></i> {% trans "Ignore rule" %}</button>
                <button type="button" id="confirmrule" onclick="jobj.changeRule('confirm');" class="btn btn-danger btn-sm pull-right panel-buttons-sm width-120" title="{% trans 'Confirm rule and reject blocked emails' %}"><i class="icmn-cross2"></i> {% trans "Confirm rule" %}</button>
                <button type="button" id="fliprule" onclick="jobj.changeRule('flip');" class="btn btn-warning btn-sm pull-right panel-buttons-sm width-120" title="{% trans 'Turn rule active state' %}"><i class="icmn-cross2"></i> {% trans "Flip rule" %}</button>
                {% endif %}
                <button type="button" id="showrule" onclick="$('#popup-modal .modal-content').html(''); $('#popup-modal').attr('data-action','show.autorule'); $('#popup-modal').modal();" class="btn btn-info btn-sm pull-right panel-buttons-sm width-120" title="{% trans 'Show emails linked to this rule' %}"><i class="icmn-info"></i> {% trans "Show messages" %}</button>
                <h5><small><i class="icmn-list"></i></small> {% trans "Autorules" %}</h5>
            </div>
            <div class="panel-body">
                <table class="table table-hover nowrap table-compact" style="table-layout: fixed;" id="autorule-table" width="100%">
                    <thead>
                    <tr>
                        <th class="never">ID</th>
                        <th>{% trans "Confirmed" %}</th>
                        <th>{% trans "Date" %}</th>
                        <th>{% trans "Name" %}</th>
                        <th>{% trans "Value" %}</th>
                        <th>{% trans "#Msgs" %}</th>
                        <th>{% trans "Active" %}</th>
                    </tr>
                    </thead>
                    <tbody>
                    </tbody>
                </table>
            </div>
        </section>
    </div>
</div>
<div class="modal fade modal-size-large" id="popup-modal" tabindex="-1" role="dialog" aria-labelledby="" aria-hidden="true">
<div class="modal-dialog" role="document">
    <div class="modal-content">
    </div>
</div>
</div>
{% endblock %}

dogoweb/spam/templates/spam/autorulesp.html
{% extends "base_menu.html" %}
{% load i18n %}
{% load seg_tags %}
{% block titulo %}{% trans "Pending Autorules" %}{% endblock %}

{% block encabezadomenu %}
    <script>var noTZ; if ("{% settings_value "DBENGINE" %}" == "mysql") { noTZ=true; } else { noTZ=false; } </script>
    <script src="/static/spam/js/autorules.js"></script>
{% endblock %}

{% block contenidomenu %}
<div class="row row-top-15">
    <div class="col-lg-2">
        <section class="panel panel-with-borders panel-compact">
            <div class="panel-heading">
                <h5><small><i class="icmn-search"></i></small> {% trans "Search" %}</h5>
            </div>
            <div class="panel-body">
                {% with WIDGET_BASE_CLASS='form-control' WIDGET_GROUP_CLASS='form-group' WIDGET_REQUIRED_CLASS='form-control-required' WIDGET_ERROR_LIST_CLASS='form-control-error' WIDGET_ERROR_CLASS='has-danger' %}
                <form id='busca_form' method="post">
                    {% csrf_token %}
                    <input type="hidden" id="id_confirmada" value="3"/>
                    <input type="hidden" id="id_activo" value="2"/>
                    <div class="row">
                        <div class="col-lg-6">
                            <button type="button" class="btn" onclick="document.getElementById('busca_form').reset();{{ form.activo.id_for_label }}_rd_reset();{{ form.confirmada.id_for_label }}_rd_reset();jobj.buscar();">{% trans "Clear" %}</button>
                        </div>
                        <div class="col-lg-6 text-right">
                            <button type="button" class="btn btn-primary" id="id_btn_buscar" onclick="jobj.buscar();">{% trans "Search" %}</button>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="form-group">
                                <input type="text" name="descripcion" class="form-control" id="id_descripcion" placeholder='{% trans "Name" %}'/>
                                <script>$('#id_descripcion').focus();</script>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="form-group">
                                <input type="text" name="valor" class="form-control" id="id_valor" placeholder='{% trans "Value" %}'/>
                            </div>
                        </div>
                    </div>
                    <div id="gr_msgcant" class="form-group">
                        <div class="row">
                            <div class="col-lg-12">
                                <label class="form-control-label" for="id_rcv_from">{% trans "Message Count" %}</label>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-6 col-compact-left">
                                    <input type="text" name="mincant" class="form-control" id="id_mincant" placeholder="{% trans 'Min' %}"/>
                            </div>
                            <div class="col-lg-6 col-compact-right">
                                <input type="text" name="maxcant" class="form-control" id="id_maxcant" placeholder="{% trans 'Max' %}"/>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="row">
                            <div class="col-lg-12">
                                <label class="form-control-label" for="id_rcv_from">{% trans "Date" %}</label>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-12">
                                <input type="text" name="rcv_from" class="form-control datetimepicker-init" id="id_rcv_from" placeholder='{% trans "From" %}'>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-12">
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-12">
                                <input type="text" name="rcv_until" class="form-control datetimepicker-init" id="id_rcv_until" placeholder='{% trans "To" %}'>
                            </div>
                        </div>
                    </div>
                </form>
                {% endwith %}
            </div>
        </section>
    </div>
    <div class="col-lg-10">
        <section class="panel panel-with-borders panel-compact">
            <div class="panel-heading">
                {% if perms.spam.change_autoreglas %}
                <button type="button" id="ignorerule" onclick="jobj.changeRule('ignore');" class="btn btn-success btn-sm pull-right panel-buttons-sm width-120" title="{% trans 'Deactivate rule and send blocked emails' %}"><i class="icmn-forward"></i> {% trans "Ignore rule" %}</button>
                <button type="button" id="confirmrule" onclick="jobj.changeRule('confirm');" class="btn btn-danger btn-sm pull-right panel-buttons-sm width-120" title="{% trans 'Confirm rule and reject blocked emails' %}"><i class="icmn-cross2"></i> {% trans "Confirm rule" %}</button>
                {% endif %}
                <button type="button" id="showrule" onclick="$('#popup-modal .modal-content').html(''); $('#popup-modal').attr('data-action','show.autorule'); $('#popup-modal').modal();" class="btn btn-info btn-sm pull-right panel-buttons-sm width-120" title="{% trans 'Show emails linked to this rule' %}"><i class="icmn-info"></i> {% trans "Show messages" %}</button>
                <h5><small><i class="icmn-list"></i></small> {% trans "Autorules" %}</h5>
            </div>
            <div class="panel-body">
                <table class="table table-hover nowrap table-compact" style="table-layout: fixed;" id="autorule-table" width="100%">
                    <thead>
                    <tr>
                        <th class="never">ID</th>
                        <th>{% trans "Confirmed" %}</th>
                        <th>{% trans "Date" %}</th>
                        <th>{% trans "Name" %}</th>
                        <th>{% trans "Value" %}</th>
                        <th>{% trans "#Msgs" %}</th>
                        <th>{% trans "Active" %}</th>
                    </tr>
                    </thead>
                    <tbody>
                    </tbody>
                </table>
            </div>
        </section>
    </div>
</div>
<div class="modal fade modal-size-large" id="popup-modal" tabindex="-1" role="dialog" aria-labelledby="" aria-hidden="true">
<div class="modal-dialog" role="document">
    <div class="modal-content">
    </div>
</div>
</div>
{% endblock %}

dogoweb/spam/templates/spam/avirus.html
{% extends "base_menu.html" %}
{% load i18n %}
{% block titulo %}{% trans "Antivirus" %}{% endblock %}

{% block encabezadomenu %}
{% endblock %}

{% block contenidomenu %}
<h1>{% trans "Antivirus" %}</h1>
{% endblock %}

dogoweb/spam/templates/spam/config.html
{% extends "base_menu.html" %}
{% load i18n %}
{% block titulo %}{% trans "Global Configuration" %}{% endblock %}

{% block encabezadomenu %}
{% endblock %}

{% block contenidomenu %}
<h1>{% trans "Global Configuration" %}</h1>
{% endblock %}

dogoweb/spam/templates/spam/form_lista.html
{% load seg_tags %}
{% load i18n %}

<div class="row">
    <div class="col-lg-6">
        {% render_field_full form.tipo %}
        {{ form.tipo|set_focus }}
    </div>
    <div class="col-lg-6">
        {% render_field_full_checkbox form.activo %}
    </div>
</div>
<div class="row">
    <div class="col-lg-6">
        {% render_field_full form.ip %}
    </div>
    <div class="col-lg-6">
        {% render_field_full form.remitente %}
    </div>
</div>
<div class="row">
    <div class="col-lg-6">
        {% render_field_full form.destino %}
    </div>
    <div class="col-lg-6">
    </div>
</div>

dogoweb/spam/templates/spam/form_module.html
{% load seg_tags %}
{% load i18n %}

<div class="row">
    <div class="col-lg-6">
        {% render_field_full form.nombre %}
        {{ form.nombre|set_focus }}
    </div>
    <div class="col-lg-6">
        {% render_field_full_checkbox form.activo %}
    </div>
</div>
<div class="row">
    <div class="col-lg-12">
        {% render_field_full form.config %}
    </div>
</div>

dogoweb/spam/templates/spam/form_policy.html
{% load seg_tags %}
{% load i18n %}

<div class="row">
    <div class="col-lg-6">
        {% render_field_full form.nombre %}
        {{ form.nombre|set_focus }}
    </div>
    <div class="col-lg-6">
        {% render_field_full_checkbox form.activo %}
    </div>
</div>